---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-testeeeee
  namespace: monitoring
  labels:
    prometheus: prometheus-app
spec:
  groups:
    - name: SRE_TEST
      rules:
        - alert: SRE_TEST
          expr: sum(process_uptime_seconds{environment="int"}) > 1
          annotations:
            title: SRE_TEST
            description: SRE_TEST
            component: SRE_TEST
            environment: int
            region: amer
            severity: info
            team: platform
            priority: P5
          labels:
            pagerduty: 'true'
            namespace: monitoring
            alertgroup: business_hours
