---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-test
  namespace: monitoring
  labels:
    prometheus: prometheus-app
spec:
  groups:
    - name: SRE_TEST
    # eeeeeeeeeee111111    eeeee     eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
      rules:
        - alert: SRE_TEST
      # Condition for alerting
      # this alert uses UTC timezone, standing for 6h-18h in PST.
          expr: sum(sum_over_time(tms_avs_execution_duration_seconds_sum{avs_service="MICROBILT",
            cluster=~"amer-pro-us.*"}[10m])) / sum(sum_over_time(tms_avs_execution_duration_seconds_count{avs_service="MICROBILT",
            cluster=~"amer-pro-us.*"}[10m])) >3
      # for: 6h
      # Annotation - additional informational labels to store more information
          annotations:
            title: SRE_TEST
            description: SRE_TEST
            component: SRE_TEST
            environment: int
            region: amer
            severity: info
            team: platform
            priority: P5

      # Labels - additional labels to be attached to the alert
          labels:
            pagerduty: 'true'
            namespace: monitoring
            alertgroup: business_hours
