---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-testt
  namespace: monitoring
  labels:
    prometheus: prometheus-app
spec:
  groups:
    - name: SRE_TEST
    # testeeeeeeeeeee1111eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
      rules:
        - alert: SRE_TEST
          expr: sum(process_uptime_seconds{environment="int"}) > 1
      # for: 6h
      # Annotation - additional informational labels to store more information
          annotations:
            title: SRE_TEST
            description: SRE_TEST
            component: SRE_TEST
            environment: int
            region: amer
            severity: info
            team: platform
            priority: P5

      # Labels - additional labels to be attached to the alert
          labels:
            pagerduty: 'true'
            namespace: monitoring
            alertgroup: business_hours
