name: Yamllint GitHub Actions
on:
  - push
jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2

      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          echo $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}) > $GITHUB_OUTPUT
      
      - name: Show me list files
        run: echo $GITHUB_OUTPUT