---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.yamllint_message.outputs.output1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Yamllint
        id: yamllint_message
        run: output1=$(yamllint $(git diff --name-only ${{ github.event.before }}
          ${{ github.sha }})) >> "$GITHUB_OUTPUTS"
  failure:
    name: fail
    if: failure()
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: out
        run: echo "${{ needs.yamllint.outputs.output1 }}"
