---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: Yamllint
    runs-on: ubuntu-latest
    outputs:
      lint_message: ${{ steps.yamllint_message.outputs.message_out }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Yamllint
        id: yamllint_message
        run: |
          message="$(yamllint $(git diff --name-only  ${{ github.event.before }} ${{ github.sha }})"
          echo message_out=$message >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: output
        run: echo "${{ steps.yamllint_message.outputs.message_out }}"
  # failure:
  #   name: Failure
  #   runs-on: ubuntu-latest
  #   needs: yamllint
  #   if: failure()
  #   steps:
  #     - name: output
  #       id: out
  #       run: echo ${{ needs.yamllint.outputs.lint_message }}
