---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.output.outputs.yamllint_output }}
      files: ${{ steps.files.outputs.files  }}
      exitcode: ${{ steps.output.outputs.exitcode}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install yamllint
        id: install
        run: sudo apt install -y yamllint
      - name: List File
        id: files
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            echo $file >> files.txt
          done
          echo "files=$(cat files.txt| tr '\n' ' ' | sed 's/ $/\n/')" >> $GITHUB_OUTPUT
      - name: Exec Yamllint
        id: exec_yamllint
        run: |
          yamllint ${{ steps.files.outputs.files }} --no-warnings > lint_result.txt && \
            echo "exitcode=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: Output
        id: output
        run: |
          if [ ${{ steps.exec_yamllint.outputs.exitcode }} -ne 0 ]; then
            echo "yamllint_output<<EOF" >> $GITHUB_OUTPUT
            cat lint_result.txt >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
          echo "Sucesso!!"
      - name: Cat output
        run: echo "${{ steps.output.outputs.yamllint_output }}"
  failure:
    name: Failure
    needs: yamllint
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output
        run: |
          echo "${{ needs.yamllint.outputs.message }}"
        shell: bash
