---
name: Yamllint GitHub Actions
on: [pull_request]
jobs:
  Yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files  }}
      yamllint_output: ${{ steps.yamllint.outputs.yamllint_output }}
      dir: ${{ steps.files.outputs.dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2
      - name: List File
        id: files
        run: |
          for file in $(git diff --name-only -r HEAD^1 HEAD); do
            echo $(dir=mkdir tmp/check_files) >> $GITHUB_OUTPUT
            echo $file >> tmp/files.txt
          done
          echo "files=$(cat files.txt| tr '\n' ' ' | sed 's/ $/\n/')" >> $GITHUB_OUTPUT
      - name: Look for bad yml files
        id: step1
        uses: theodore86/polint-github-action@v2
        with:
          path: ${{ steps.files.outputs.dir }}
          exclude: .*git.*

      # - name: Yamllint
      #   id: yamllint
      #   uses: karancode/yamllint-github-action@master
      #   with:
      #     yamllint_file_or_dir: ${{ steps.files.outputs.files }}
      #     yamllint_strict: false
      #     yamllint_comment: true
      #     yamllint_config_datapath: relaxed
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
