---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      message: ${{ steps.exec_yamllint.outputs.message }}
      files: ${{ steps.files.outputs.files  }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install yamllint
        id: install
        run: sudo apt install -y yamllint
      - name: List File
        id: files
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }}); do
            echo $file >> files.txt
          done
          echo "files=$(cat files.txt| tr '\n' ' ' | sed 's/ $/\n/')" >> $GITHUB_OUTPUT
      - name: Exec Yamllint
        id: exec_yamllint
        run: |
          yamllint ${{ steps.files.outputs.files }} --no-warnings > lint_result.txt
          echo "message=$(cat lint_result.txt)" >> $GITHUB_OUTPUT
        continue-on-error: true
      - name: Test
        run: cat lint_result.txt
      - name: Cat test
        run: echo ${{ steps.exec_yamllint.outputs.message }}
        # - name: Yamllint
      #   id: yamllint
      #   uses: karancode/yamllint-github-action@v2.1.1
      #   with:
      #     yamllint_file_or_dir: ${{ steps.files.outputs.files }}
      #     yamllint_strict: false
      #     yamllint_comment: true
      #   env:
      #     GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # failure:
  #   name: Failure
  #   needs: yamllint
  #   if: failure()
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Output
  #       run: ${{  needs.yamllint.outputs.message  }}
