---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.yamllint_message.outputs.test }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Yamllint
        id: yamllint_message
        run: echo "test=$(yamllint $(git diff --name-only ${{ github.event.before }}
          ${{ github.sha }}))"
        continue-on-error: true
      - name: test
        run: echo $test >> $GITHUB_ENV
  failure:
    name: fail
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: out
        run: echo "${{ env.test }}"

        # jobs:
        #   job1:
        #     runs-on: ubuntu-latest
        #  # Map a step output to a job output
        #     outputs:
        #       output1: ${{ steps.step1.outputs.test }}
        #       output2: ${{ steps.step2.outputs.test }}
        #     steps:
        #       - id: step1
        #         run: echo "test=hello" >> "$GITHUB_OUTPUT"
        #       - id: step2
        #         run: echo "test=world" >> "$GITHUB_OUTPUT"
        #   job2:
        #     runs-on: ubuntu-latest
        #     needs: job1
        #     steps:
        #       - env:
        #           OUTPUT1: ${{needs.job1.outputs.output1}}
        #           OUTPUT2: ${{needs.job1.outputs.output2}}
        #         run: echo "$OUTPUT1 $OUTPUT2"
