---
name: Yamllint GitHub Actions
on: [pull_request, push]
jobs:
  Yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files  }}
      yamllint_output: ${{ steps.yamllint.outputs.yamllint_output }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: List File
        id: files
        run: |
          echo "files<<EOF" >> $GITHUB_OUTPUT
          git diff --name-only --diff-filter=d -r HEAD^1 HEAD | grep -E '\.(yaml|yml)$'>> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Yamllint
        id: yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: ${{ steps.files.outputs.files }}
          yamllint_strict: false
          yamllint_comment: true
          yamllint_config_datapath: relaxed
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
