---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: Yamllint   
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 2
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Yamllint
        id: yamllint_message
        run: yamllint $(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
