---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.test.outputs.output1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          echo git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      # - name: Yamllint
      #   id: yamllint_message
      #   run: echo "output1=$(yamllint $(git diff --name-only ${{ github.event.before }}
      #     ${{ github.sha }}) --no-warning)" >> $GITHUB_OUTPUT
      #   continue-on-error: true
      - name: Test
        id: test
        run: |
          echo "output1=$(cat test4.yaml)" >> $GITHUB_OUTPUT
      # - name: Yamllint
      #   id: message
      #   uses: mathiasvr/command-output@v2.0.0
      #   with:
      #     run: echo "stdout=$(yamllint $(git diff --name-only ${{ github.event.before }}
      #       ${{ github.sha }}) --no-warning)"
  teste:
    name: teste
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: teste
        run: echo ${{ needs.yamllint.outputs.output1 }}
