---
name: Yamllint GitHub Actions
on: [push, pull_request]
jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.yamllint_message.outputs.output1 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          fetch-depth: 0
      - name: Install yamllint
        run: sudo apt install -y yamllint
      - name: List files
        id: list_files
        run: |
          echo "Getting modified files..."
          echo git diff --name-only ${{ github.event.before }} ${{ github.sha }}
      - name: Yamllint
        id: yamllint_message
        run: |
          echo "::set-output name=output1::$(yamllint teste3.yaml)"
        continue-on-error: true
      - name: Test
        run: echo ${{ steps.yamllint_message.outputs.output1 }}
  teste:
    name: teste
    runs-on: ubuntu-latest
    needs: yamllint
    steps:
      - name: teste
        run: echo ${{ needs.yamllint.outputs.output1 }}
