---
name: Yamllint GitHub Actions
on: [pull_request, push]
jobs:
  Yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files.outputs.files  }}
      yamllint_output: ${{ steps.yamllint.outputs.yamllint_output }}
    steps:
      - name: teste
        run: exit 1
